window.RESIDENTIAL_DATA = {
  "generated_at": "2026-04-29T00:00:40.914571",
  "scan_date": "2026-04-29",
  "deals": [
    {
      "address": "123 East Main Street",
      "city": "Waterbury",
      "state": "CT",
      "type": "duplex",
      "category": "value-add",
      "asking_price": 250000,
      "estimated_monthly_rent": 3200,
      "estimated_annual_noi": 19200,
      "cap_rate_pct": 10.0,
      "gross_yield_pct": 15.4,
      "work_required": "Cosmetic updates to both units, full roof replacement, minor HVAC and plumbing upgrades",
      "time_commitment_hrs_week": 15,
      "down_payment_20pct": 50000,
      "monthly_cashflow_estimate": 270,
      "source": "connecticutrealestate.online",
      "url": "https://connecticutrealestate.online/multifamily-real-estate-investment-in-waterbury-ct-2025/",
      "r1_verdict": "PASS",
      "r1_rationale": "High renovation costs ($50k estimated) make total investment $300k+ for projected ARV of $192k (based on 10% cap rate). Negative equity position and B-class location vacancy risk outweighs rent growth potential. Better opportunities exist.",
      "risk_flags": [
        "renovation_cost_overruns",
        "vacancy_during_reno",
        "Waterbury economic volatility",
        "roof/HVAC surprises",
        "cap_rate compression risk"
      ]
    },
    {
      "address": "456 Willow Avenue",
      "city": "Tolland",
      "state": "CT",
      "type": "triplex",
      "category": "value-add",
      "asking_price": 420000,
      "estimated_monthly_rent": 4800,
      "estimated_annual_noi": 28800,
      "cap_rate_pct": 9.5,
      "gross_yield_pct": 13.7,
      "work_required": "Full cosmetic renovations (kitchens/baths), electrical system updates + common area improvements",
      "time_commitment_hrs_week": 20,
      "down_payment_20pct": 84000,
      "monthly_cashflow_estimate": 165,
      "source": "connecticutrealestate.online",
      "url": "https://connecticutrealestate.online/multifamily-investing-connecticut-2026-cap-rates-opportunities/",
      "r1_verdict": "RESEARCH",
      "r1_rationale": "Pro forma returns rely on flawless execution - $70k+ rehab could push total investment to $490k vs $303k ARV (9.5% cap). $55/door cashflow too thin for ops time required. Verify renovation bids and comps.",
      "risk_flags": [
        "electrical_upgrade_costs",
        "contractor_availability",
        "Tolland renter demand uncertainty",
        "interest_rate_hikes",
        "post-reno appraisal gap"
      ]
    },
    {
      "address": "789 Elm Street",
      "city": "Manchester",
      "state": "NH",
      "type": "duplex",
      "category": "turnkey",
      "asking_price": 450000,
      "estimated_monthly_rent": 4000,
      "estimated_annual_noi": 28800,
      "cap_rate_pct": 6.4,
      "gross_yield_pct": 10.7,
      "work_required": "None - tenant occupied with property management included. Walk-up maintenance reserve only.",
      "time_commitment_hrs_week": 1,
      "down_payment_20pct": 90000,
      "monthly_cashflow_estimate": 406,
      "source": "Market Data",
      "url": "https://newenglandturnkey.properties/nh-listings",
      "r1_verdict": "PURSUE",
      "r1_rationale": "Stabilized cashflow requires $0 ops time with included property mgmt. Manchester growth supports 4% rent hikes. CoC return ~5.4% beats REITs with NH's landlord-friendly laws. Ideal for passive allocation.",
      "risk_flags": [
        "turnkey_premium_pricing",
        "property_mgmt_quality",
        "NH property tax increases",
        "single-market exposure"
      ]
    },
    {
      "address": "101 Oak Avenue",
      "city": "Worcester",
      "state": "MA",
      "type": "triplex",
      "category": "turnkey",
      "asking_price": 650000,
      "estimated_monthly_rent": 6000,
      "estimated_annual_noi": 43200,
      "cap_rate_pct": 6.6,
      "gross_yield_pct": 11.1,
      "work_required": "Minor exterior maintenance per inspection report (fence repair, gutter cleaning). 3-year roof certification in place.",
      "time_commitment_hrs_week": 2,
      "down_payment_20pct": 130000,
      "monthly_cashflow_estimate": 712,
      "source": "Market Data",
      "url": "https://masslandlords.com/turnkey-providers",
      "r1_verdict": "PURSUE",
      "r1_rationale": "Strong Worcester demand ensures 95% occupancy. Immediate ~$700/month cashflow scales with college/medical tenant base. Price justifies MA growth fundamentals with minimal oversight needed.",
      "risk_flags": [
        "higher_entry_price",
        "MA rent control speculation",
        "college_market seasonality",
        "inflation_impact_on_ops_costs"
      ]
    }
  ],
  "summary": " The user wants a 3-4 sentence plain-language summary for Dhruv Patel covering:\n1. Best single opportunity and why\n2. Total capital needed across all 4 if pursued\n3. One key risk to watch\n\nFirst, I need to identify all 4 deals. The user provided 2 complete deals in the prompt, but the prompt cuts off after the second deal's rationale. However, looking carefully, only 2 deals are fully shown. Wait, let me check again.\n\nActually, the prompt says \"Summarize these 4 residential investment opportunities\" but only provides 2 complete JSON objects. The second one is cut off mid-rationale. There are clearly only 2 deals shown in the input, but the prompt mentions 4. \n\nWait, looking more carefully:\n- Deal 1: 123 East Main Street, Waterbury, CT - duplex\n- Deal 2: 456 Willow Avenue, Tolland, CT - triplex\n\nThe prompt cuts off after the second deal's rationale. It seems like the user may have intended to provide 4 but only provided 2, or the other 2 got lost. However, as the assistant, I should work with what's provided. But the user explicitly asks for \"Total capital needed across all 4 if pursued\" - this implies there should be 4 deals. \n\nActually, looking at the prompt again, I see the array starts with `[` and there are two objects fully shown, but the prompt might be truncated. Since I can only see 2 deals, I have two options:\n1. Ask for the missing 2 deals\n2. Assume they only want me to summarize based on what's visible and calculate total for the visible ones (but they specifically say \"all 4\")\n\nWait, perhaps I should look more carefully. The user input shows:\nDeals:\n[\n  { ... deal 1 ... },\n  { ... deal 2 ... }\n]\n\nAnd that's it. Only 2 deals are provided despite saying 4. However, the user might have made an error, or the other 2 are implied to be there but got cut off. Since I need to provide a helpful answer, I should probably note that only 2 were provided, OR I should just answer based on the 2 deals shown but adjust the \"across all 4\" to \"across both\" or similar.\n\nActually, looking at the request again: \"Summarize these 4",
  "value_add_count": 2,
  "turnkey_count": 2,
  "pursue_count": 2,
  "total_capital_needed": 354000
};