// Protected by protect_goals.py — blacklisted goals removed, statuses enforced
window.SPRINT_GOALS_DATA = {
  "exported_at": "2026-04-28T10:45:02Z",
  "total": 21,
  "by_status": {
    "not_started": 21
  },
  "by_category": {
    "family": 3,
    "cre": 3,
    "wealth": 8,
    "advisor": 2,
    "health": 1,
    "ops": 1,
    "personal": 3
  },
  "goals": [
    {
      "goal_id": "kavita-hysa-entity",
      "category": "family",
      "title": "Kavita call: HYSA entity question (personal vs S-Corp)",
      "description": "",
      "deadline": "2026-04-24",
      "status": "not_started",
      "priority": "critical",
      "notes": "",
      "created_at": "2026-04-19T04:09:07.769627",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.5,
      "deep_work_action": "Call kavitha@shahdixit.com",
      "start_by": "2026-04-21"
    },
    {
      "goal_id": "nnn-first",
      "category": "cre",
      "title": "First NNN asset closed",
      "description": "",
      "deadline": "2026-09-30",
      "status": "not_started",
      "priority": "critical",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 40.0,
      "deep_work_action": "LoopNet/Crexi search: MA, 8-10% cap, $20K+ rent. Run through cre-evaluator.",
      "start_by": "2026-04-25"
    },
    {
      "goal_id": "axos-open",
      "category": "wealth",
      "title": "Open Axos HYSA — $75K",
      "description": "",
      "deadline": "2026-04-30",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-19T04:09:07.769627",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.5,
      "deep_work_action": "Open axosbank.com HYSA, wire $75K from Bluestone",
      "start_by": "2026-04-25"
    },
    {
      "goal_id": "sofi-open",
      "category": "wealth",
      "title": "Open SoFi HYSA — $25K",
      "description": "",
      "deadline": "2026-04-30",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-19T04:09:07.769627",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.5,
      "deep_work_action": "Open SoFi savings, fund $25K",
      "start_by": "2026-04-25"
    },
    {
      "goal_id": "voo-vig",
      "category": "wealth",
      "title": "Deploy $60K VOO+VIG from Bluestone",
      "description": "$50K VOO + $10K VIG. Transfer from Bluestone to Merrill then execute trades.",
      "deadline": "2026-12-31",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 1.0,
      "deep_work_action": "Wire $60K Bluestone → Merrill, then execute $50K VOO + $10K VIG trades",
      "start_by": "2026-05-01"
    },
    {
      "goal_id": "insurance",
      "category": "family",
      "title": "Life + disability insurance",
      "description": "",
      "deadline": "2026-06-30",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 2.0,
      "deep_work_action": "Call insurance broker, get quotes for both partners, fill app",
      "start_by": "2026-05-01"
    },
    {
      "goal_id": "cre-brokers",
      "category": "cre",
      "title": "3 active broker relationships for NNN deals",
      "description": "",
      "deadline": "2026-06-30",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-19T04:09:07.769627",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 2.0,
      "deep_work_action": "Contact LoopNet brokers, CBRE, Marcus & Millichap MA offices",
      "start_by": "2026-04-20"
    },
    {
      "goal_id": "kavita-1031",
      "category": "advisor",
      "title": "1031 planning meeting with Kavita",
      "description": "",
      "deadline": "2026-06-30",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 1.5,
      "deep_work_action": "Email Kavita to schedule 1031 planning session, prep AMDA financials",
      "start_by": "2026-05-15"
    },
    {
      "goal_id": "preconception",
      "category": "health",
      "title": "Preconception checkups — both partners",
      "description": "",
      "deadline": "2026-07-31",
      "status": "not_started",
      "priority": "medium",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 3.0,
      "deep_work_action": "Book appointments for both partners, compile medical history",
      "start_by": "2026-06-01"
    },
    {
      "goal_id": "529-ready",
      "category": "family",
      "title": "529 plan ready",
      "description": "",
      "deadline": "2026-09-30",
      "status": "not_started",
      "priority": "medium",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 2.0,
      "deep_work_action": "Research 529 plan options (Fidelity/Vanguard), open account",
      "start_by": "2026-08-01"
    },
    {
      "goal_id": "cre-pipeline-5",
      "category": "cre",
      "title": "5+ NNN pipeline deals evaluated via CRE Evaluator",
      "description": "",
      "deadline": "2026-10-31",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-19T04:09:07.769627",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.5,
      "deep_work_action": "Use eval: trigger in Telegram for each deal from brokers",
      "start_by": "2026-05-01"
    },
    {
      "goal_id": "ops-boundary",
      "category": "ops",
      "title": "AMDA ops boundary — 2hr max daily",
      "description": "Enforce 2-hour AMDA ops limit. Hire/delegate so deep work block is protected.",
      "deadline": "2026-10-17",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-18",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.0,
      "deep_work_action": "Review who handles what. Define escalation path so you aren't default firefighter.",
      "start_by": "2026-04-25"
    },
    {
      "goal_id": "marriage-presence",
      "category": "personal",
      "title": "Be actually present with wife — not just physically there",
      "description": "Phones off 6:30-9PM daily. Friday date night 7-10PM protected. Weekly finance meeting. Quality over quantity.",
      "deadline": "2026-10-17",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-18",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.0,
      "deep_work_action": "This is a daily habit not a project. Track it in habits. Review weekly.",
      "start_by": "2026-04-19"
    },
    {
      "goal_id": "identity-investor",
      "category": "wealth",
      "title": "Shift identity: investor who owns a store, not store operator who invests",
      "description": "The store is an asset, not a job. You allocate capital.",
      "deadline": "2026-10-17",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-18",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.0,
      "deep_work_action": "Measure: how many hours/week on capital allocation vs store operations? Target: 80/20.",
      "start_by": "2026-04-19"
    },
    {
      "goal_id": "emergency-fund",
      "category": "wealth",
      "title": "Emergency fund $75K pre-baby",
      "description": "",
      "deadline": "2026-10-17",
      "status": "not_started",
      "priority": "medium",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 1.0,
      "deep_work_action": "Track Bluestone balance monthly, ensure $75K reserved before baby",
      "start_by": "2026-09-01"
    },
    {
      "goal_id": "lcid-harvest",
      "category": "wealth",
      "title": "LCID tax-loss harvest decision",
      "description": "$15,836 harvestable loss. Offsets TSLA gains. 31-day wash sale rule.",
      "deadline": "2026-12-31",
      "status": "not_started",
      "priority": "high",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.5,
      "deep_work_action": "Execute LCID sell in Merrill, wait 31 days for wash sale, optionally rebuy",
      "start_by": "2026-10-01"
    },
    {
      "goal_id": "kavita-amda",
      "category": "advisor",
      "title": "AMDA standalone valuation with Kavita",
      "description": "",
      "deadline": "2026-12-31",
      "status": "not_started",
      "priority": "medium",
      "notes": "",
      "created_at": "2026-04-18T22:24:23Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 3.0,
      "deep_work_action": "Compile AMDA financials, schedule valuation meeting with Kavita",
      "start_by": "2026-10-01"
    },
    {
      "goal_id": "smr-nne-review",
      "category": "wealth",
      "title": "SMR/NNE Q3 decision: hold or exit?",
      "description": "Review SMR/NNE thesis — both down 43-67%. Decide hold or harvest losses.",
      "deadline": "2026-09-30",
      "status": "not_started",
      "priority": "medium",
      "notes": "",
      "created_at": "2026-04-18",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 1.0,
      "deep_work_action": "Pull 1yr chart, check nuclear permitting news, make hold/exit call",
      "start_by": "2026-08-01"
    },
    {
      "goal_id": "marriage-trip",
      "category": "personal",
      "title": "Plan a real trip with wife — just the two of you",
      "description": "Before baby. Somewhere meaningful. Not a weekend, a real trip.",
      "deadline": "2026-12-31",
      "status": "not_started",
      "priority": "medium",
      "notes": "",
      "created_at": "2026-04-18",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 2.0,
      "deep_work_action": "Pick destination, book it. Budget from discretionary. Don't defer this.",
      "start_by": "2026-07-01"
    },
    {
      "goal_id": "parents-quality-time",
      "category": "personal",
      "title": "Scheduled quality time with parents — monthly minimum",
      "description": "Not just showing up for events. Intentional time. Dinners, calls, presence.",
      "deadline": "2026-12-31",
      "status": "not_started",
      "priority": "medium",
      "notes": "",
      "created_at": "2026-04-18",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.0,
      "deep_work_action": "Block first Sunday of each month for parents. Put it in calendar now.",
      "start_by": "2026-05-01"
    },
    {
      "goal_id": "roth-ira",
      "category": "wealth",
      "title": "Roth IRA contribution — 2026 max",
      "description": "Max out Roth IRA for 2026 ($7,000). Coordinate with Asha re: S-Corp 401k strategy.",
      "deadline": "2026-12-31",
      "status": "not_started",
      "priority": "medium",
      "notes": "",
      "created_at": "2026-04-23T21:25:00Z",
      "updated_at": "2026-04-23T21:25:00Z",
      "time_estimate_hrs": 0.5,
      "deep_work_action": "Check income eligibility, max contribution via Merrill or Fidelity",
      "start_by": "2026-10-01"
    }
  ]
};